/*
 * This source file was generated by the Gradle 'init' task
 */
package rockpaperscissors;

import org.junit.jupiter.api.Test;

import de.pandabrrito.rockpaperscissors.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
